---
services:
  flowcase:
    image: ghcr.io/vigno04/flowcase:latest
    container_name: ${WEB_CONTAINER_NAME:-flowcase-web}
    restart: unless-stopped
    volumes:
      - flowcase-data:/flowcase/data
      - flowcase-nginx-data:/flowcase/nginx
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - FLASK_APP=run.py
      - FLASK_DEBUG=${FLASK_DEBUG:-0}
      - NGINX_CONTAINER_NAME=${NGINX_CONTAINER_NAME:-flowcase-nginx}
      - FLOWCASE_NETWORK=${FLOWCASE_NETWORK:-flowcase_default_network}
    networks:
      - default_network
    command: python run.py

  nginx:
    image: nginx:1.28-alpine
    container_name: ${NGINX_CONTAINER_NAME:-flowcase-nginx}
    restart: unless-stopped
    ports:
      - "${PORT:-80}:80"
    volumes:
      - flowcase-nginx-data:/etc/nginx/conf.d
    depends_on:
      - flowcase
    networks:
      - default_network

networks:
  default_network:
    name: ${FLOWCASE_NETWORK:-flowcase_default_network}
    driver: bridge

volumes:
  flowcase-data:
    external: false
  flowcase-nginx-data:
    external: false
